/camera:
  ros__parameters:
    camera:
      i_nn_type: none
      i_enable_ir: false
      i_pipeline_type: RGBStereo
    pipeline_gen:
      i_enable_imu: true # Set to false when we replace with VN-200
    right:
      i_publish_topic: true
    left:
      i_publish_topic: true
    rgb:
      i_set_isp_scale: false
